services:
  brokerr:
    container_name: brokerr
    volumes:
      - /data/configs/brokerr:/config
    build:
      context: .
    depends_on:
      # redis:
      #   condition: "service_started"
      #   required: false
    ports:
      - 6363:6363
    environment:
      - PUID=1000
      - PGID=1000

  # redis:
  #   container_name: brokerr-redis
  #   image: redis:alpine