# syntax=docker/dockerfile:1

FROM python:3.12.2-slim-bookworm

ENV GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz"

#ARG PUID=1000
#ARG PGUID=1000

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

ENV DEBIAN_FRONTEND="noninteractive"

WORKDIR /

# Create a non-root user
#RUN addgroup --gid $PGUID brokerr-group && \
#    adduser --disabled-password --gecos '' --uid $PUID --gid $PGUID brokerr-user && \
    # install packages

    # First remove firefox snap package so we can install DEB
RUN apt-get update && apt-get install -y \
    firefox-esr wget python3-pip \
    && wget $GECKODRIVER_URL -O geckodriver-v0.34.0-linux64.tar.gz && \
    tar -xzf geckodriver-v0.34.0-linux64.tar.gz -C /usr/bin && \
    chmod +x /usr/bin/geckodriver && \
    rm -f geckodriver-v0.34.0-linux64.tar.gz \
    && export PATH=$PATH:/usr/bin/

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    pip install --no-build-isolation -r requirements.txt

COPY brokerr /brokerr

WORKDIR /brokerr/app

EXPOSE 6363

# Switch to the specified user
#USER myuser:mygroup

CMD ["python3", "main.py" ]